In [1]:
import numpy as np
import scipy.io

In [25]:
chianti_emiss_tbl = scipy.io.readsav("../../sav/AWSoM/chianti_table/AWSoM_UCoMP_emiss.sav",verbose=True,python_dict=True)

--------------------------------------------------
Date: Mon Nov 21 08:21:02 2022
User: Yingjie
Host: DESKTOP-8RK6URI
--------------------------------------------------
Format: 12
Architecture: x86_64
Operating System: Win32
IDL Version: 8.5
--------------------------------------------------
Successfully read 16 records of which:
 - 13 are of type VARIABLE
 - 1 are of type TIMESTAMP
 - 1 are of type VERSION
--------------------------------------------------
Available variables:
 - fexiv_emiss_array [<class 'numpy.ndarray'>]
 - fex_emiss_array [<class 'numpy.ndarray'>]
 - fexi_emiss_array [<class 'numpy.ndarray'>]
 - fexiii_10747_emiss_array [<class 'numpy.ndarray'>]
 - fexiii_10798_emiss_array [<class 'numpy.ndarray'>]
 - fexv_emiss_array [<class 'numpy.ndarray'>]
 - sviii_emiss_array [<class 'numpy.ndarray'>]
 - sxii_emiss_array [<class 'numpy.ndarray'>]
 - nixv_6703_emiss_array [<class 'numpy.ndarray'>]
 - nixv_8026_emiss_array [<class 'numpy.ndarray'>]
 - temp [<class 'numpy.ndarray

In [26]:
np.where(chianti_emiss_tbl["dens"] == 8)

(array([12]),)

In [27]:
np.where(chianti_emiss_tbl["temp"] == 6)

(array([20]),)

In [28]:
np.where(chianti_emiss_tbl["height"] == 1.1)

(array([2]),)

In [29]:
chianti_emiss_tbl["fexiv_emiss_array"][2,12,20]*1e8*1

6.187170829712782e-13

In [14]:
np.log10(0.83)+16

15.919078092376074