In [7]:
import numpy as np
import scipy.io
from scipy import interpolate

In [2]:
chianti_emiss_tbl = scipy.io.readsav("../../sav/AWSoM/chianti_table/AWSoM_UCoMP_emiss_4Rsun.sav",verbose=True,python_dict=True)

--------------------------------------------------
Date: Wed Nov 23 16:29:47 2022
User: Yingjie
Host: DESKTOP-8RK6URI
--------------------------------------------------
Format: 12
Architecture: x86_64
Operating System: Win32
IDL Version: 8.5
--------------------------------------------------
Successfully read 16 records of which:
 - 13 are of type VARIABLE
 - 1 are of type TIMESTAMP
 - 1 are of type VERSION
--------------------------------------------------
Available variables:
 - fexiv_emiss_array [<class 'numpy.ndarray'>]
 - fex_emiss_array [<class 'numpy.ndarray'>]
 - fexi_emiss_array [<class 'numpy.ndarray'>]
 - fexiii_10747_emiss_array [<class 'numpy.ndarray'>]
 - fexiii_10798_emiss_array [<class 'numpy.ndarray'>]
 - fexv_emiss_array [<class 'numpy.ndarray'>]
 - sviii_emiss_array [<class 'numpy.ndarray'>]
 - sxii_emiss_array [<class 'numpy.ndarray'>]
 - nixv_6703_emiss_array [<class 'numpy.ndarray'>]
 - nixv_8026_emiss_array [<class 'numpy.ndarray'>]
 - temp [<class 'numpy.ndarray

In [3]:
np.where(chianti_emiss_tbl["dens"] == 8)

(array([12]),)

In [12]:
np.where(chianti_emiss_tbl["temp"] == 6.3)

(array([26]),)

In [13]:
np.where(chianti_emiss_tbl["height"] == 1.1)

(array([2]),)

In [14]:
chianti_emiss_tbl["fexiv_emiss_array"][2,12,26]*1e8*1

9.115704885443614e-10

In [15]:
emiss_func = interpolate.RegularGridInterpolator(points=(chianti_emiss_tbl["height"],chianti_emiss_tbl["dens"],chianti_emiss_tbl["temp"]),
                    values=chianti_emiss_tbl["fexiv_emiss_array"],
                    bounds_error=False,method="linear")

In [20]:
emiss_func((1.1,8,6.3))*1e8/0.83*1e11

109.82770639200186

In [24]:
emiss_func((1.2,8,6))*1e8/0.83*1e11

0.07103030051666141

In [25]:
emiss_func((1.2,8,6.3))*1e8/0.83*1e11

103.91845138365329

In [26]:
emiss_func((1.2,7,6.3))*1e7/0.83*1e11

2.9120098523703417

In [27]:
emiss_func((1.2,7,6.4))*1e7/0.83*1e11

1.1843605943693774